// LNGCNV VERSION 1.2.0 / THE MIT LICENSE (MIT) © 2022 PIOTR BAJDEK

use std::env;
use std::process::exit;

fn fake_main() -> i32 {1} // exit

fn main() {

   let clear = "\x1b[0m"; // reset the font color
   let bright_yellow = "\x1b[93m"; //  font color

// ARGUMENTS ANYWHERE WITHIN THE STRING

   for argument in env::args() {

// ABOUT

      if argument == "-a" || argument == "--about" {
      println!("Program:  lngcnv");
      println!("Version:  1.2.0");
      println!("Date:     February 11, 2022");
      println!("Author:   Piotr Bajdek (Poland)");
      println!("Contact:  piotr.bajdek@protonmail.com");
      println!("Source:   https://github.com/piotrbajdek/lngcnv");
      println!("License:  The MIT License (MIT) © 2022 Piotr Bajdek");
      let exit_code = fake_main();
      exit(exit_code);
      }

// CHANGES

      if argument == "-c" || argument == "--changes" {
      println!("11.02.2022 v1.2.0 – Added --ipa --que");
      println!("09.02.2022 v1.1.0 – Added --ipa --pol");
      println!("07.02.2022 v1.0.0 – The first release of lngcnv (--ipa --lat; --ipa --tca; --ort --eng; --ort --lat; --ort --que; --ort --tca)");
      let exit_code = fake_main();
      exit(exit_code);
      }

// HELP

      if argument == "-h" || argument == "--help" {
      print!("{}", bright_yellow);
      println!("Usage:    lngcnv [OPTION 1/2] [OPTION 2/1] [STRING]");
      print!("{}", clear);
      println!("");
      println!("OPTION 1: --ipa  Transcribe [STRING] into the International Phonetic Alphabet");
      println!("          --ort  Convert [STRING] between regional norms of orthography");
      println!("");
      println!("OPTION 2: --eng  English | available for:        --ort");
      println!("          --lat  Latin   | available for: --ipa, --ort");
      println!("          --pol  Polish  | available for: --ipa");
      println!("          --que  Quechua | available for: --ipa, --ort");
      println!("          --tca  Tikuna  | available for: --ipa, --ort");
      println!("");
      print!("{}", bright_yellow);
      println!("Examples: lngcnv --ipa --lat 'Vēnī, vīdī, vīcī.'");
      println!("          lngcnv --lat --ipa 'Vēnī, vīdī, vīcī.'");
      print!("{}", clear);
      println!("");
      println!("          For multi-word queries always use single or double quotation marks!");
      println!("          For word strings including apostrophes, use double quotation.");
      println!("");
      println!("See also: -a, --about     Show contact and program info");
      println!("          -c, --changes   Show change notes");
      println!("          -h, --help      Show this help");
      println!("          -l, --languages Show notes on the languages supported");
      println!("          -L, --license   Show licesing information");
      println!("          -v, --version   Show the program version");
      let exit_code = fake_main();
      exit(exit_code);
      }

// LANGUAGES

      if argument == "-l" || argument == "--languages" {
      print!("{}", bright_yellow);
      println!("English:");
      print!("{}", clear);
      println!("          In the --ort mode, the text is transcribed into American English.");
      println!("");
      print!("{}", bright_yellow);
      println!("Latin:");
      print!("{}", clear);
      println!("          The modern spelling of Latin and the ancient convention can be used indifferently. To mark the duration of vowels, type either apices or macrons. In the --ort mode, the text is transcribed into the ancient convention (before the 2nd c. AD).");
      println!("");
      print!("{}", bright_yellow);
      println!("Polish:");
      print!("{}", clear);
      println!("          Częstochowa (south-central Poland) is characterised by a fairly 'neutral-sounding' accent.");
      println!("");
      print!("{}", bright_yellow);
      println!("Quechua:");
      print!("{}", clear);
      println!("          In the --ipa mode, Ayacucho Quechua is implemented and the input must be spelled accordingly (although the algorithm is able to partially convert from Cusco Quechua). The --ort mode allows transcribing between the trivocalic and the pentavocalic orthographies and works fine with any language of the Quechuan Family.");
      println!("");
      print!("{}", bright_yellow);
      println!("Tikuna:");
      print!("{}", clear);
      println!("          Two variants of pronunciation (Nazareth, CO; Umariaçu, BR) (--ipa) and four distinct orthographies (--ort) are supported. There is no support for tones at this stage of program development. Even so, in the --ipa mode tonal letters can be displayed if inserted manually as numbers beginning from 1 (the lowest) to 5 (the highest tone). Abbreviations: ILV - Instituto Lingüístico de Verano; FORMABIAP - Formación de Maestros Bilingües de la Amazonía Peruana");
      let exit_code = fake_main();
      exit(exit_code);
      }

// LICENSE

      if argument == "-L" || argument == "--license" {
      print!("{}", bright_yellow);
      println!("The MIT License (MIT)");
      print!("{}", clear);
      println!("");
      println!("Copyright © 2022 Piotr Bajdek");
      println!("");
      println!("Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:");
      println!("");
      println!("The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.");
      println!("");
      println!("THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.");
      let exit_code = fake_main();
      exit(exit_code);
      }

// VERSION

      if argument == "-v" || argument == "--version" {
      println!("Version: 1.2.0");
      println!("February 11, 2022");
      let exit_code = fake_main();
      exit(exit_code);
      }

   }

// COLLECT ARGUMENTS FOR CONVERSIONS

   let args: Vec<String> = env::args().collect();

   let input1 = args.get(1).expect("Invalid or missing arguments! See: --help");
   let input2 = args.get(2).expect("Invalid or missing arguments! See: --help");

// ENGLISH: ORTHOGRAPHY

   if input1 == "--ort" && input2 == "--eng" || input1 == "--eng" && input2 == "--ort" {

   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("celling", "celing");
   let str3 = &str2.replace("delling", "deling");
   let str4 = &str3.replace("velling", "veling");
   let str5 = &str4.replace("bour", "bor");
   let str6 = &str5.replace("iour", "ior");
   let str7 = &str6.replace("nour", "nor");
   let str8 = &str7.replace("olour", "olor");
   let str9 = &str8.replace("centre", "center");
   let str10 = &str9.replace("metre", "meter");
   let str11 = &str10.replace("theatre", "theater");
   let str12 = &str11.replace("fence", "fense");
   let str13 = &str12.replace("lise", "lize");
   let str14 = &str13.replace("lyse", "lyze");
   let str15 = &str14.replace("sation", "zation");
   let str16 = &str15.replace("aestetic", "estetic");
   let str17 = &str16.replace("Aestetic", "Estetic");
   let str18 = &str17.replace("faec", "fec");
   let str19 = &str18.replace("Faec", "Fec");
   let str20 = &str19.replace("palaeo", "paleo");
   let str21 = &str20.replace("Palaeo", "Paleo");
   let str22 = &str21.replace("manoeuvre", "maneuver");
   let str23 = &str22.replace("aluminium", "aluminum");
   let str24 = &str23.replace("Aluminium", "Aluminum");
   let str25 = &str24.replace(" axe ", " ax ");
   let str26 = &str25.replace(" axe,", " ax,");
   let str27 = &str26.replace(" axe.", " ax.");
   let str28 = &str27.replace("cheque", "check");
   let str29 = &str28.replace("cumquat", "kumquat");
   let str30 = &str29.replace("fulfil", "fulfill");
   let str31 = &str30.replace("fulfilll", "fulfill");
   let str32 = &str31.replace("Fulfil", "Fulfill");
   let str33 = &str32.replace("Fulfilll", "Fulfill");
   let str34 = &str33.replace("grey", "gray");
   let str35 = &str34.replace("Grey", "Gray");
   let str36 = &str35.replace("kerb", "curb");
   let str37 = &str36.replace("moustache", "mustache");
   let str38 = &str37.replace("mum ", "mom ");
   let str39 = &str38.replace("mum,", "mom,");
   let str40 = &str39.replace("mum.", "mom.");
   let str41 = &str40.replace("Mum,", "Mom,");
   let str42 = &str41.replace("programme", "program");
   let str43 = &str42.replace("Programme", "Program");
   let str44 = &str43.replace("sceptical", "skeptical");
   let str45 = &str44.replace("Sceptical", "Skeptical");
   let str46 = &str45.replace("CELLING", "CELING");
   let str47 = &str46.replace("DELLING", "DELING");
   let str48 = &str47.replace("VELLING", "VELING");
   let str49 = &str48.replace("BOUR", "BOR");
   let str50 = &str49.replace("IOUR", "IOR");
   let str51 = &str50.replace("NOUR", "NOR");
   let str52 = &str51.replace("OLOUR", "OLOR");
   let str53 = &str52.replace("CENTRE", "CENTER");
   let str54 = &str53.replace("METRE", "METER");
   let str55 = &str54.replace("THEATRE", "THEATER");
   let str56 = &str55.replace("FENCE", "FENSE");
   let str57 = &str56.replace("LISE", "LIZE");
   let str58 = &str57.replace("LYSE", "LYZE");
   let str59 = &str58.replace("SATION", "ZATION");
   let str60 = &str59.replace("AESTETIC", "ESTETIC");
   let str61 = &str60.replace("FAEC", "FEC");
   let str62 = &str61.replace("PALAEO", "PALEO");
   let str63 = &str62.replace("MANOEUVRE", "MANEUVER");
   let str64 = &str63.replace("ALUMINIUM", "ALUMINUM");
   let str65 = &str64.replace(" AXE ", " AX ");
   let str66 = &str65.replace(" AXE,", " AX,");
   let str67 = &str66.replace(" AXE.", " AX.");
   let str68 = &str67.replace("CHEQUE", "CHECK");
   let str69 = &str68.replace("CUMQUAT", "KUMQUAT");
   let str70 = &str69.replace("FULFIL", "FULFILL");
   let str71 = &str70.replace("FULFILLL", "FULFILL");
   let str72 = &str71.replace("GREY", "GRAY");
   let str73 = &str72.replace("KERB", "CURB");
   let str74 = &str73.replace("MOUSTACHE", "MUSTACHE");
   let str75 = &str74.replace("MUM ", "MOM ");
   let str76 = &str75.replace("MUM,", "MOM,");
   let str77 = &str76.replace("MUM.", "MOM.");
   let str78 = &str77.replace("PROGRAMME", "PROGRAM");
   let result = &str78.replace("SCEPTICAL", "SKEPTICAL");
   println!("");
   println!("American English:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// LATIN: IPA

   if input1 == "--ipa" && input2 == "--lat" || input1 == "--lat" && input2 == "--ipa" {

   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("A", "a");
   let str3 = &str2.replace("Ā", "ā");
   let str4 = &str3.replace("Á", "ā");
   let str5 = &str4.replace("B", "b");
   let str6 = &str5.replace("bs", "ps");
   let str7 = &str6.replace("bt", "pt");
   let str8 = &str7.replace("C", "c");
   let str9 = &str8.replace("D", "d");
   let str10 = &str9.replace("E", "e");
   let str11 = &str10.replace("Ē", "ē");
   let str12 = &str11.replace("É", "ē");
   let str13 = &str12.replace("Ë", "ë");
   let str14 = &str13.replace("F", "f");
   let str15 = &str14.replace("G", "ɡ");
   let str16 = &str15.replace("g", "ɡ");
   let str17 = &str16.replace("H", "h");
   let str18 = &str17.replace("I", "i");
   let str19 = &str18.replace("Ī", "ī");
   let str20 = &str19.replace("Í", "ī");
   let str21 = &str20.replace("ꟾ", "ī");
   let str22 = &str21.replace("J", "j");
   let str23 = &str22.replace("K", "k");
   let str24 = &str23.replace("L", "l");
   let str25 = &str24.replace("M", "m");
   let str26 = &str25.replace("N", "n");
   let str27 = &str26.replace("O", "o");
   let str28 = &str27.replace("Ō", "ō");
   let str29 = &str28.replace("Ó", "ō");
   let str30 = &str29.replace("P", "p");
   let str31 = &str30.replace("Q", "q");
   let str32 = &str31.replace("R", "r");
   let str33 = &str32.replace("S", "s");
   let str34 = &str33.replace("T", "t");
   let str35 = &str34.replace("V", "u");
   let str36 = &str35.replace("v", "u");
   let str37 = &str36.replace("uu", "vu");
   let str38 = &str37.replace("ui", "vi");
   let str39 = &str38.replace("ue", "ve");
   let str40 = &str39.replace("ua", "va");
   let str41 = &str40.replace("uo", "vo");
   let str42 = &str41.replace("uũ", "vũ");
   let str43 = &str42.replace("uī", "vī");
   let str44 = &str43.replace("uē", "vē");
   let str45 = &str44.replace("uā", "vā");
   let str46 = &str45.replace("uō", "vō");
   let str47 = &str46.replace("U", "u");
   let str48 = &str47.replace("Ū", "ū");
   let str49 = &str48.replace("Ú", "ū");
   let str50 = &str49.replace("Ü", "ü");
   let str51 = &str50.replace("W", "w");
   let str52 = &str51.replace("X", "x");
   let str53 = &str52.replace("Y", "y");
   let str54 = &str53.replace("Ȳ", "ȳ");
   let str55 = &str54.replace("Ý", "ý");
   let str56 = &str55.replace("Z", "z");
   let str57 = &str56.replace("Ă", "ă");
   let str58 = &str57.replace("Ĕ", "ĕ");
   let str59 = &str58.replace("Ĭ", "ĭ");
   let str60 = &str59.replace("Ŏ", "ŏ");
   let str61 = &str60.replace("Ŭ", "ŭ");
   let str62 = &str61.replace("Y̆", "y̆");
   let str63 = &str62.replace("s", "s̺");
   let str64 = &str63.replace("s̺b", "s̬b");
   let str65 = &str64.replace("s̺d", "s̬d");
   let str66 = &str65.replace("s̺ɡ", "s̬ɡ");
   let str67 = &str66.replace("s̺m", "s̬m");
   let str68 = &str67.replace("s̺n", "s̬n");
   let str69 = &str68.replace("nd", "md");
   let str70 = &str69.replace("n d", "m d");
   let str71 = &str70.replace("np", "mp");
   let str72 = &str71.replace("n p", "m p");
   let str73 = &str72.replace("nf", "ɱf");
   let str74 = &str73.replace("n f", "ɱ f");
   let str75 = &str74.replace("nm", "mm");
   let str76 = &str75.replace("n m", "m m");
   let str77 = &str76.replace("nq", "ŋq");
   let str78 = &str77.replace("n q", "ŋ q");
   let str79 = &str78.replace("nc", "ŋc");
   let str80 = &str79.replace("n c", "ŋ c");
   let str81 = &str80.replace("c", "k");
   let str82 = &str81.replace("q", "k");
   let str83 = &str82.replace("ii", "jː");
   let str84 = &str83.replace("l", "ɫ");
   let str85 = &str84.replace("ɫɫ", "ll");
   let str86 = &str85.replace("ɫi", "li");
   let str87 = &str86.replace("rh", "r̥");
   let str88 = &str87.replace("v", "w");
   let str89 = &str88.replace("x", "k͡s̺");
   let str90 = &str89.replace("ɡn", "ŋn");
   let str91 = &str90.replace("ë", "ɛ");
   let str92 = &str91.replace("ü", "u̞");
   let str93 = &str92.replace("ĕr", "ær");
   let str94 = &str93.replace("ie", "īe");
   let str95 = &str94.replace("cum", "kʉm");
   let str96 = &str95.replace("ptim", "ptɨm");
   let str97 = &str96.replace("crim", "krɨm");
   let str98 = &str97.replace("um ", "ũː ");
   let str99 = &str98.replace("um,", "ũː,");
   let str100 = &str99.replace("um.", "ũː.");
   let str101 = &str100.replace("um?", "ũː?");
   let str102 = &str101.replace("um!", "ũː!");
   let str103 = &str102.replace("um·", "ũː·");
   let str104 = &str103.replace("em ", "ɛ̝̃ː ");
   let str105 = &str104.replace("em,", "ɛ̝̃ː,");
   let str106 = &str105.replace("em;", "ɛ̝̃ː;");
   let str107 = &str106.replace("em.", "ɛ̝̃ː.");
   let str108 = &str107.replace("em?", "ɛ̝̃ː?");
   let str109 = &str108.replace("em!", "ɛ̝̃ː!");
   let str110 = &str109.replace("em·", "ɛ̝̃ː·");
   let str111 = &str110.replace("ens", "ɛ̝̃ːs̺");
   let str112 = &str111.replace("ons", "ɔ̝̃ːs̺");
   let str113 = &str112.replace("inf", "ĩːf");
   let str114 = &str113.replace("er", "ær");
   let str115 = &str114.replace("ia", "ja");
   let str116 = &str115.replace("ii", "jː");
   let str117 = &str116.replace("io", "jo");
   let str118 = &str117.replace("iu", "ju");
   let str119 = &str118.replace("iā", "jā");
   let str120 = &str119.replace("iī", "jː");
   let str121 = &str120.replace("iō", "jō");
   let str122 = &str121.replace("iū", "jū");
   let str123 = &str122.replace("ea", "ia");
   let str124 = &str123.replace("ae", "ɐɛ̯");
   let str125 = &str124.replace("oe", "ɔɛ̯");
   let str126 = &str125.replace("i", "i̞");
   let str127 = &str126.replace("o", "ɔ");
   let str128 = &str127.replace("u", "u̞");
   let str129 = &str128.replace("y", "ʏ");
   let str130 = &str129.replace("a", "ɐ");
   let str131 = &str130.replace("e", "ɛ");
   let str132 = &str131.replace("ā", "ɐː");
   let str133 = &str132.replace("á", "ɐː");
   let str134 = &str133.replace("ē", "ɛ̝ː");
   let str135 = &str134.replace("é", "ɛ̝ː");
   let str136 = &str135.replace("ī", "iː");
   let str137 = &str136.replace("í", "iː");
   let str138 = &str137.replace("ō", "ɔ̝ː");
   let str139 = &str138.replace("ó", "ɔ̝ː");
   let str140 = &str139.replace("ū", "uː");
   let str141 = &str140.replace("ú", "uː");
   let str142 = &str141.replace("ȳ", "yː");
   let str143 = &str142.replace("ý", "yː");
   let str144 = &str143.replace("ă", "ɐ");
   let str145 = &str144.replace("ĕ", "ɛ");
   let str146 = &str145.replace("ĭ", "i̞");
   let str147 = &str146.replace("ŏ", "ɔ");
   let str148 = &str147.replace("ŭ", "u̞");
   let str149 = &str148.replace("y̆", "ʏ");
   let str150 = &str149.replace(",", " ∣");
   let str151 = &str150.replace(";", " ∥");
   let str152 = &str151.replace(":", " ∣");
   let str153 = &str152.replace(". ", " ∥ ");
   let str154 = &str153.replace(".", "");
   let str155 = &str154.replace("! ", " ∥ ");
   let str156 = &str155.replace("!", "");
   let str157 = &str156.replace("? ", " ∥ ");
   let str158 = &str157.replace("?", "");
   let str159 = &str158.replace("(", "∣ ");
   let str160 = &str159.replace(")", " ∣");
   let str161 = &str160.replace("·", " ");
   let str162 = &str161.replace(" - ", " ∣ ");
   let str163 = &str162.replace(" – ", " ∣ ");
   let result = &str163.replace("--", " ∣ ");
   println!("");
   println!("Classical Latin:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// LATIN: ORTHOGRAPHY

   if input1 == "--ort" && input2 == "--lat" || input1 == "--lat" && input2 == "--ort" {

   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("a", "A");
   let str3 = &str2.replace("á", "Á");
   let str4 = &str3.replace("ă", "A");
   let str5 = &str4.replace("ā", "Á");
   let str6 = &str5.replace("b", "B");
   let str7 = &str6.replace("c", "C");
   let str8 = &str7.replace("d", "D");
   let str9 = &str8.replace("e", "E");
   let str10 = &str9.replace("ĕ", "E");
   let str11 = &str10.replace("é", "É");
   let str12 = &str11.replace("ē", "É");
   let str13 = &str12.replace("ë", "E");
   let str14 = &str13.replace("f", "F");
   let str15 = &str14.replace("g", "G");
   let str16 = &str15.replace("h", "H");
   let str17 = &str16.replace("i", "I");
   let str18 = &str17.replace("ĭ", "I");
   let str19 = &str18.replace("Ī", "ꟾ");
   let str20 = &str19.replace("ī", "ꟾ");
   let str21 = &str20.replace("í", "ꟾ");
   let str22 = &str21.replace("Í", "ꟾ");
   let str23 = &str22.replace("j", "I");
   let str24 = &str23.replace("k", "K");
   let str25 = &str24.replace("l", "L");
   let str26 = &str25.replace("m", "M");
   let str27 = &str26.replace("n", "N");
   let str28 = &str27.replace("o", "O");
   let str29 = &str28.replace("ŏ", "O");
   let str30 = &str29.replace("ō", "Ó");
   let str31 = &str30.replace("p", "P");
   let str32 = &str31.replace("q", "Q");
   let str33 = &str32.replace("r", "R");
   let str34 = &str33.replace("s", "S");
   let str35 = &str34.replace("t", "T");
   let str36 = &str35.replace("u", "V");
   let str37 = &str36.replace("v", "V");
   let str38 = &str37.replace("ú", "Ú");
   let str39 = &str38.replace("ŭ", "V");
   let str40 = &str39.replace("ū", "Ú");
   let str41 = &str40.replace("ü", "V");
   let str42 = &str41.replace("w", "VV");
   let str43 = &str42.replace("x", "X");
   let str44 = &str43.replace("y", "Y");
   let str45 = &str44.replace("y̆", "Y");
   let str46 = &str45.replace("ȳ", "Ý");
   let str47 = &str46.replace("ý", "Ý");
   let str48 = &str47.replace("z", "Z");
   let str49 = &str48.replace("Ă", "A");
   let str50 = &str49.replace("Ā", "Á");
   let str51 = &str50.replace("Ĕ", "E");
   let str52 = &str51.replace("Ë", "E");
   let str53 = &str52.replace("Ĭ", "I");
   let str54 = &str53.replace("Ī", "ꟾ");
   let str55 = &str54.replace("Í", "ꟾ");
   let str56 = &str55.replace("J", "I");
   let str57 = &str56.replace("Ŏ", "O");
   let str58 = &str57.replace("Ō", "Ó");
   let str59 = &str58.replace("Ŭ", "V");
   let str60 = &str59.replace("Ū", "Ú");
   let str61 = &str60.replace("Ü", "V");
   let str62 = &str61.replace("Y̆", "Y");
   let str63 = &str62.replace("Ȳ", "Ý");
   let str64 = &str63.replace(" - ", "·");
   let str65 = &str64.replace(" – ", "·");
   let str66 = &str65.replace("--", "·");
   let str67 = &str66.replace(", ", "·");
   let str68 = &str67.replace("; ", "·");
   let str69 = &str68.replace(": ", "·");
   let str70 = &str69.replace(". ", "·");
   let str71 = &str70.replace("! ", "·");
   let str72 = &str71.replace("? ", "·");
   let str73 = &str72.replace(".", "");
   let str74 = &str73.replace("!", "");
   let str75 = &str74.replace("?", "");
   let result = &str75.replace(" ", "·");
   println!("");
   println!("Classical Latin:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// POLISH: IPA

   if input1 == "--ipa" && input2 == "--pol" || input1 == "--pol" && input2 == "--ipa" {

   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.to_lowercase();
   let str3 = &str2.replace("dż", "ɖ͡ʐ");
   let str4 = &str3.replace("dzi", "d͡ʑi");
   let str5 = &str4.replace("dź", "d͡ʑ");
   let str6 = &str5.replace("rdz", "ɾd̪͡z̪");
   let str7 = &str6.replace("rd", "ɾd̪");
   let str8 = &str7.replace("dz", "d͡z");
   let str9 = &str8.replace("ód", "ód̥");
   let str10 = &str9.replace("dcz", "d̥cz");
   let str11 = &str10.replace("dt", "d̥t");
   let str12 = &str11.replace("dk", "d̥k");
   let str13 = &str12.replace("t", "t̪");
   let str14 = &str13.replace("st̪rz", "ʂʈ͡ʂ");
   let str15 = &str14.replace("t̪rz", "ṯʃ");
   let str16 = &str15.replace("prz", "pʂ");
   let str17 = &str16.replace("t̪r", "ṯɾ̥");
   let str18 = &str17.replace("rt̪", "ɾ̥ṯ");
   let str19 = &str18.replace("t̪m", "ṯm̥");
   let str20 = &str19.replace("izn", "is̬n̥");
   let str21 = &str20.replace("zn", "zn̥");
   let str22 = &str21.replace("ans", "an̥s");
   let str23 = &str22.replace("ącz", "ąṉcz");
   let str24 = &str23.replace("sz", "ʃ");
   let str25 = &str24.replace("śln", "śl̥n");
   let str26 = &str25.replace("ślm", "śl̥m");
   let str27 = &str26.replace("śń", "śɲ̥");
   let str28 = &str27.replace("ń", "ɲ");
   let str29 = &str28.replace("ni", "ɲi");
   let str30 = &str29.replace("mc", "m̥c");
   let str31 = &str30.replace("nc", "n̥c");
   let str32 = &str31.replace("ch", "χ");
   let str33 = &str32.replace("h", "x");
   let str34 = &str33.replace("ś", "ɕ");
   let str35 = &str34.replace("s", "s̻");
   let str36 = &str35.replace("cz", "ʈ͡ʂ");
   let str37 = &str36.replace("ci", "t͡ɕi");
   let str38 = &str37.replace("c", "t͡s");
   let str39 = &str38.replace("ć", "t͡ɕ");
   let str40 = &str39.replace("χrz", "χʂ");   
   let str41 = &str40.replace("rz", "ʒ");
   let str42 = &str41.replace("r", "ɾ");
   let str43 = &str42.replace("ż", "ʒ");
   let str44 = &str43.replace("ź", "ʑ");
   let str45 = &str44.replace("ng", "ŋɡ");
   let str46 = &str45.replace("nk", "ŋk");
   let str47 = &str46.replace("g", "ɡ");
   let str48 = &str47.replace("wk", "v̥k");
   let str49 = &str48.replace("w", "v");
   let str50 = &str49.replace("bł", "b̥w̥");
   let str51 = &str50.replace("ł", "w");
   let str52 = &str51.replace("im", "i̞ɱ");
   let str53 = &str52.replace("in", "i̞ŋ");
   let str54 = &str53.replace("ia", "i̞a");
   let str55 = &str54.replace("io", "i̞o");
   let str56 = &str55.replace("ie", "i̞e");
   let str57 = &str56.replace("iu", "i̞ü");
   let str58 = &str57.replace("ju", "jü");
   let str59 = &str58.replace("i", "i̞");
   let str60 = &str59.replace("aʈ͡ʂ", "ɐʈ͡ʂ");
   let str61 = &str60.replace("ʈ͡ʂa", "ʈ͡ʂɐ");
   let str62 = &str61.replace("at͡s", "ɐt͡s");
   let str63 = &str62.replace("t͡sa", "t͡sɐ");
   let str64 = &str63.replace("aʃ", "ɐʃ");
   let str65 = &str64.replace("ʃa", "ʃɐ");
   let str66 = &str65.replace("s̻a", "s̻ɐ");
   let str67 = &str66.replace("as̻", "ɐs̻");
   let str68 = &str67.replace("am", "aɱ");
   let str69 = &str68.replace("an", "aŋ");
   let str70 = &str69.replace("a", "ä");
   let str71 = &str70.replace("eʈ͡ʂ", "ɛ̝̈ʈ͡ʂ");
   let str72 = &str71.replace("ʈ͡ʂe", "ʈ͡ʂɛ̝̈");
   let str73 = &str72.replace("et͡s", "ɛ̝̈t͡s");
   let str74 = &str73.replace("t͡se", "t͡sɛ̝̈");
   let str75 = &str74.replace("eʃ", "ɛ̝̈ʃ");
   let str76 = &str75.replace("ʃe", "ʃɛ̝̈");
   let str77 = &str76.replace("s̻e", "s̻ɛ̝̈");
   let str78 = &str77.replace("es̻", "ɛ̝̈s̻");
   let str79 = &str78.replace("em", "ɛ̝ɱ");
   let str80 = &str79.replace("en", "ɛ̝ŋ");
   let str81 = &str80.replace("e", "ɛ̝");
   let str82 = &str81.replace("ę", "ɛ̝̃");
   let str83 = &str82.replace("oʈ͡ʂ", "ɔ̝̈ʈ͡ʂ");
   let str84 = &str83.replace("ʈ͡ʂo", "ʈ͡ʂɔ̝̈");
   let str85 = &str84.replace("ot͡s", "ɔ̝̈t͡s");
   let str86 = &str85.replace("t͡so", "t͡sɔ̝̈");
   let str87 = &str86.replace("oʃ", "ɔ̝̈ʃ");
   let str88 = &str87.replace("ʃo", "ʃɔ̝̈");
   let str89 = &str88.replace("s̻o", "s̻ɔ̝̈");
   let str90 = &str89.replace("os̻", "ɔ̝̈s̻");
   let str91 = &str90.replace("om", "ɔ̝ɱ");
   let str92 = &str91.replace("on", "ɔ̝ŋ");
   let str93 = &str92.replace("o", "ɔ̝");
   let str94 = &str93.replace("ą", "ɔ̝̃");
   let str95 = &str94.replace("ó", "u");
   let str96 = &str95.replace("um", "u̞ɱ");
   let str97 = &str96.replace("un", "u̞ŋ");
   let str98 = &str97.replace("u", "u̞");
   let str99 = &str98.replace("yʈ͡ʂ", "ɘʈ͡ʂ");
   let str100 = &str99.replace("ʈ͡ʂy", "ʈ͡ʂɘ");
   let str101 = &str100.replace("yt͡s", "ɘt͡s");
   let str102 = &str101.replace("t͡sy", "t͡sɘ");
   let str103 = &str102.replace("yʃ", "ɘʃ");
   let str104 = &str103.replace("ʃy", "ʃɘ");
   let str105 = &str104.replace("s̻y", "s̻ɘ");
   let str106 = &str105.replace("ys̻", "ɘs̻");
   let str107 = &str106.replace("ym", "ɘ̟ɱ");
   let str108 = &str107.replace("yn", "ɘ̟ŋ");
   let str109 = &str108.replace("y", "ɘ̟");
   let str110 = &str109.replace(",", " ∣");
   let str111 = &str110.replace(";", " ∥");
   let str112 = &str111.replace(":", " ∣");
   let str113 = &str112.replace(". ", " ∥ ");
   let str114 = &str113.replace(".", "");
   let str115 = &str114.replace("! ", " ∥ ");
   let str116 = &str115.replace("!", "");
   let str117 = &str116.replace("? ", " ∥ ");
   let str118 = &str117.replace("?", "");
   let str119 = &str118.replace("(", "∣ ");
   let str120 = &str119.replace(")", " ∣");
   let str121 = &str120.replace(" - ", " ∣ ");
   let str122 = &str121.replace(" – ", " ∣ ");
   let result = &str122.replace("--", " ∣ ");
   println!("");
   println!("Polish (Częstochowa):");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// AYACUCHO QUECHUA: IPA

   if input1 == "--ipa" && input2 == "--que" || input1 == "--que" && input2 == "--ipa" {

   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.to_lowercase();
   let str3 = &str2.replace("sh", "ch");
   let str4 = &str3.replace("chh", "ch");
   let str5 = &str4.replace("kh", "k");
   let str6 = &str5.replace("th", "t");
   let str7 = &str6.replace("ph", "p");
   let str8 = &str7.replace("qh", "q");
   let str9 = &str8.replace("j", "q");
   let str10 = &str9.replace("'", "");
   let str11 = &str10.replace("’", "");
   let str12 = &str11.replace("qu", "qo");
   let str13 = &str12.replace("uq", "oq");
   let str14 = &str13.replace("qi", "qe");
   let str15 = &str14.replace("iq", "eq");
   let str16 = &str15.replace("an", "aŋ");
   let str17 = &str16.replace("ma", "mæ");
   let str18 = &str17.replace("mis", "mɪ̝s̻");
   let str19 = &str18.replace("mich", "mɪ̝ch");
   let str20 = &str19.replace("cha", "chä");
   let str21 = &str20.replace("ch", "ʧ");
   let str22 = &str21.replace("g", "ɡ");
   let str23 = &str22.replace("ka", "kæ̞");
   let str24 = &str23.replace("da", "dæ");
   let str25 = &str24.replace("d", "d̥");
   let str26 = &str25.replace("lla", "llæ");
   let str27 = &str26.replace("ll", "ʎ");
   let str28 = &str27.replace("ñ", "ɲ");
   let str29 = &str28.replace("pa", "pä");
   let str30 = &str29.replace("f", "f̟");
   let str31 = &str30.replace("q", "χ");
   let str32 = &str31.replace("r", "ɾ");
   let str33 = &str32.replace("ɾχ", "ɾ̥χ");
   let str34 = &str33.replace("sa", "s̻ä");
   let str35 = &str34.replace("s", "s̻");
   let str36 = &str35.replace("ci", "s̻i");
   let str37 = &str36.replace("ce", "s̻e");
   let str38 = &str37.replace("z", "s̻");
   let str39 = &str38.replace("t", "t̪");
   let str40 = &str39.replace("wa", "wæ");   
   let str41 = &str40.replace("ya", "yæ");
   let str42 = &str41.replace("y", "j");
   let str43 = &str42.replace("o", "ʊ̞");
   let str44 = &str43.replace("e", "ɪ̞");
   let str45 = &str44.replace("u", "u̞");
   let str46 = &str45.replace("i", "i̞");
   let str47 = &str46.replace(",", " ∣");
   let str48 = &str47.replace(";", " ∥");
   let str49 = &str48.replace(":", " ∣");
   let str50 = &str49.replace(". ", " ∥ ");
   let str51 = &str50.replace(".", "");
   let str52 = &str51.replace("! ", " ∥ ");
   let str53 = &str52.replace("!", "");
   let str54 = &str53.replace("¡", "");
   let str55 = &str54.replace("? ", " ∥ ");
   let str56 = &str55.replace("?", "");
   let str57 = &str56.replace("¿", "");
   let str58 = &str57.replace("(", "∣ ");
   let str59 = &str58.replace(")", " ∣");
   let str60 = &str59.replace(" - ", " ∣ ");
   let str61 = &str60.replace(" – ", " ∣ ");
   let result = &str61.replace("--", " ∣ ");
   println!("");
   println!("Ayacucho Quechua (Wanta):");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// QUECHUA: ORTHOGRAPHY

   if input1 == "--ort" && input2 == "--que" || input1 == "--que" && input2 == "--ort" {
// TRIVOCALIC
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("o", "u");
   let str3 = &str2.replace("O", "U");
   let str4 = &str3.replace("e", "i");
   let result = &str4.replace("E", "I");
   println!("");
   println!("Trivocalic:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
// PENTAVOCALIC
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("qu", "qo");
   let str3 = &str2.replace("Qu", "Qo");
   let str4 = &str3.replace("QU", "QO");
   let str5 = &str4.replace("qi", "qe");
   let str6 = &str5.replace("Qi", "Qe");
   let str7 = &str6.replace("QI", "QE");
   let str8 = &str7.replace("qhu", "qho");
   let str9 = &str8.replace("Qhu", "Qho");
   let str10 = &str9.replace("QHU", "QHO");
   let str11 = &str10.replace("qhi", "qhe");
   let str12 = &str11.replace("Qhi", "Qhe");
   let str13 = &str12.replace("QHI", "QHE");
   let str14 = &str13.replace("ko", "ku");
   let str15 = &str14.replace("Ko", "Ku");
   let str16 = &str15.replace("KO", "KU");
   let str17 = &str16.replace("ke", "ki");
   let str18 = &str17.replace("Ke", "Ki");
   let str19 = &str18.replace("KE", "KI");
   let str20 = &str19.replace("kho", "khu");
   let str21 = &str20.replace("Kho", "Khu");
   let str22 = &str21.replace("KHO", "KHU");
   let str23 = &str22.replace("khe", "khi");
   let str24 = &str23.replace("Khe", "Khi");
   let str25 = &str24.replace("KHE", "KHI");
   let str26 = &str25.replace("q'u", "q'o");
   let str27 = &str26.replace("Q'u", "Q'o");
   let str28 = &str27.replace("Q'U", "Q'O");
   let str29 = &str28.replace("q'i", "q'e");
   let str30 = &str29.replace("Q'i", "Q'e");
   let str31 = &str30.replace("Q'I", "Q'E");
   let str32 = &str31.replace("q’u", "q’o");
   let str33 = &str32.replace("Q’u", "Q’o");
   let str34 = &str33.replace("Q’U", "Q’O");
   let str35 = &str34.replace("q’i", "q’e");
   let str36 = &str35.replace("Q’i", "Q’e");
   let str37 = &str36.replace("Q’I", "Q’E");
   let str38 = &str37.replace("uq", "oq");
   let str39 = &str38.replace("Uq", "Oq");
   let str40 = &str39.replace("UQ", "OQ");
   let str41 = &str40.replace("iq", "eq");
   let str42 = &str41.replace("Iq", "Eq");
   let result = &str42.replace("IQ", "EQ");
   println!("");
   println!("Pentavocalic:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// TIKUNA: IPA

   if input1 == "--ipa" && input2 == "--tca" || input1 == "--tca" && input2 == "--ipa" {
// IPA: NAZARETH
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("1", "˩");
   let str3 = &str2.replace("2", "˨");
   let str4 = &str3.replace("3", "˧");
   let str5 = &str4.replace("4", "˦");
   let str6 = &str5.replace("5", "˥");
   let str7 = &str6.replace("x", "ʔ");
   let str8 = &str7.replace("X", "ʔ");
   let str9 = &str8.replace("'", "ʔ");
   let str10 = &str9.replace("’", "ʔ");
   let str11 = &str10.replace("B", "β");
   let str12 = &str11.replace("CUE", "kUE");
   let str13 = &str12.replace("CUI", "kUI");
   let str14 = &str13.replace("C", "k");
   let str15 = &str14.replace("TkH", "CH");
   let str16 = &str15.replace("kH", "CH");
   let str17 = &str16.replace("CH", "ʧ");
   let str18 = &str17.replace("D", "d");
   let str19 = &str18.replace("NG", "ŋ");
   let str20 = &str19.replace("G", "ɡ");
   let str21 = &str20.replace("M", "m");
   let str22 = &str21.replace("N", "n̪");
   let str23 = &str22.replace("NH", "Ñ");
   let str24 = &str23.replace("Ñ", "ɲ");
   let str25 = &str24.replace("P", "p");
   let str26 = &str25.replace("QUE", "kE");
   let str27 = &str26.replace("QUI", "kI");
   let str28 = &str27.replace("Q", "k");
   let str29 = &str28.replace("R", "ɾ");
   let str30 = &str29.replace("T", "t̪");
   let str31 = &str30.replace("W", "ɰ");
   let str32 = &str31.replace("Y", "d͡ʒ");
   let str33 = &str32.replace("J", "d͡ʒ");
   let str34 = &str33.replace("F", "ɸ");
   let str35 = &str34.replace("L", "l");
   let str36 = &str35.replace("Z", "S");
   let str37 = &str36.replace("Ç", "S");
   let str38 = &str37.replace("S", "s̺");
   let str39 = &str38.replace("V", "ɰ");
   let str40 = &str39.replace("b", "β");
   let str41 = &str40.replace("w", "ɰ");
   let str42 = &str41.replace("v", "ɰ");
   let str43 = &str42.replace("cue", "kue");
   let str44 = &str43.replace("Cue", "kue");
   let str45 = &str44.replace("cui", "kui");
   let str46 = &str45.replace("Cui", "kui");
   let str47 = &str46.replace("c", "k");
   let str48 = &str47.replace("tkh", "ch");
   let str49 = &str48.replace("Tkh", "ch");
   let str50 = &str49.replace("kh", "ch");
   let str51 = &str50.replace("Kh", "ch");
   let str52 = &str51.replace("ch", "ʧ");
   let str53 = &str52.replace("d", "d");
   let str54 = &str53.replace("Nɡ", "ŋ");
   let str55 = &str54.replace("ng", "ŋ");
   let str56 = &str55.replace("g", "ɡ");
   let str57 = &str56.replace("n", "n̪");
   let str58 = &str57.replace("nh", "ñ");
   let str59 = &str58.replace("Nh", "ñ");
   let str60 = &str59.replace("ñ", "ɲ");
   let str61 = &str60.replace("que", "ke");
   let str62 = &str61.replace("Que", "ke");
   let str63 = &str62.replace("qui", "ki");
   let str64 = &str63.replace("Qui", "ki");
   let str65 = &str64.replace("q", "k");
   let str66 = &str65.replace("r", "ɾ");
   let str67 = &str66.replace("t", "t̪");
   let str68 = &str67.replace("y", "d͡ʒ");
   let str69 = &str68.replace("j", "d͡ʒ");
   let str70 = &str69.replace("f", "ɸ");
   let str71 = &str70.replace("z", "s");
   let str72 = &str71.replace("ç", "s");
   let str73 = &str72.replace("s", "s̺");
   let str74 = &str73.replace("K", "k");
   let str75 = &str74.replace("ã", "ɐ̱̃");
   let str76 = &str75.replace("ü̃", "ɨ̱̃");
   let str77 = &str76.replace("a̱", "ʌ̰");
   let str78 = &str77.replace("e̱", "ë");
   let str79 = &str78.replace("i̱", "ɪ");
   let str80 = &str79.replace("o̱", "ö");
   let str81 = &str80.replace("u̱", "ṵ");
   let str82 = &str81.replace("ü̱", "ɯ̈");
   let str83 = &str82.replace("á", "a");
   let str84 = &str83.replace("é", "e");
   let str85 = &str84.replace("í", "i");
   let str86 = &str85.replace("ó", "o");
   let str87 = &str86.replace("ú", "ʉ̱");
   let str88 = &str87.replace("ǘ", "ü");
   let str89 = &str88.replace("à", "a");
   let str90 = &str89.replace("è", "e");
   let str91 = &str90.replace("ì", "i");
   let str92 = &str91.replace("ò", "o̞");
   let str93 = &str92.replace("ù", "ʉ̱");
   let str94 = &str93.replace("ǜ", "ü");
   let str95 = &str94.replace("d͡ʒae", "d͡ʒæː");
   let str96 = &str95.replace("a", "ɐ̱");
   let str97 = &str96.replace("o", "o");
   let str98 = &str97.replace("u", "ʉ̱");
   let str99 = &str98.replace("ü", "ɨ̱");
   let str100 = &str99.replace("Ã", "ɐ̱̃");
   let str101 = &str100.replace("Ẽ", "ẽ");
   let str102 = &str101.replace("Ĩ", "ĩ");
   let str103 = &str102.replace("Õ", "õ");
   let str104 = &str103.replace("Ũ", "ũ");
   let str105 = &str104.replace("Ü̃", "ɨ̱̃");
   let str106 = &str105.replace("A̱", "ʌ̰");
   let str107 = &str106.replace("E̱", "ë");
   let str108 = &str107.replace("I̱", "ɪ");
   let str109 = &str108.replace("O̱", "ö");
   let str110 = &str109.replace("U̱", "ṵ");
   let str111 = &str110.replace("Ü̱", "ɯ̈");
   let str112 = &str111.replace("Á", "ɐ̱");
   let str113 = &str112.replace("É", "e");
   let str114 = &str113.replace("Í", "i");
   let str115 = &str114.replace("Ó", "o");
   let str116 = &str115.replace("Ú", "ʉ̱");
   let str117 = &str116.replace("Ǘ", "Ü");
   let str118 = &str117.replace("À", "ɐ̱");
   let str119 = &str118.replace("È", "e");
   let str120 = &str119.replace("Ì", "i");
   let str121 = &str120.replace("Ò", "o");
   let str122 = &str121.replace("Ù", "ʉ̱");
   let str123 = &str122.replace("Ǜ", "Ü");
   let str124 = &str123.replace("d͡ʒAE", "d͡ʒæː");
   let str125 = &str124.replace("A", "ɐ̱");
   let str126 = &str125.replace("E", "e");
   let str127 = &str126.replace("I", "i");
   let str128 = &str127.replace("O", "o");
   let str129 = &str128.replace("U", "ʉ̱");
   let str130 = &str129.replace("Ü", "ɨ̱");
   let str131 = &str130.replace("ʉ̱̰", "ṵ");
   let str132 = &str131.replace("n̪̪ɡ", "ŋ");
   let str133 = &str132.replace(". ", " ∥ ");
   let str134 = &str133.replace(".", "");
   let str135 = &str134.replace(",", " ∣");
   let str136 = &str135.replace(";", " ∥");
   let str137 = &str136.replace(":", " ∣");
   let str138 = &str137.replace("? ", " ∥ ");
   let str139 = &str138.replace("?", "");   
   let str140 = &str139.replace("¿", "");
   let str141 = &str140.replace("! ", " ∥ ");
   let str142 = &str141.replace("!", "");
   let str143 = &str142.replace("¡", "");
   let str144 = &str143.replace(" - ", " ∣ ");
   let str145 = &str144.replace(" – ", " ∣ ");
   let str146 = &str145.replace("--", " ∣ ");
   let str147 = &str146.replace("(", "∣ ");
   let result = &str147.replace(")", " ∣");
   println!("");
   println!("Central Tikuna (Nazareth, CO):");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
// IPA: UMARIAÇU
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("1", "˩");
   let str3 = &str2.replace("2", "˨");
   let str4 = &str3.replace("3", "˧");
   let str5 = &str4.replace("4", "˦");
   let str6 = &str5.replace("5", "˥");
   let str7 = &str6.replace("x", "ʔ");
   let str8 = &str7.replace("X", "ʔ");
   let str9 = &str8.replace("'", "ʔ");
   let str10 = &str9.replace("’", "ʔ");
   let str11 = &str10.replace("B", "β");
   let str12 = &str11.replace("CUE", "kUE");
   let str13 = &str12.replace("CUI", "kUI");
   let str14 = &str13.replace("C", "k");
   let str15 = &str14.replace("TkH", "CH");
   let str16 = &str15.replace("kH", "CH");
   let str17 = &str16.replace("CH", "ʧ");
   let str18 = &str17.replace("D", "d");
   let str19 = &str18.replace("NG", "ŋ");
   let str20 = &str19.replace("G", "ɣ");
   let str21 = &str20.replace("M", "m");
   let str22 = &str21.replace("N", "n̪");
   let str23 = &str22.replace("NH", "Ñ");
   let str24 = &str23.replace("Ñ", "ɲ");
   let str25 = &str24.replace("P", "p");
   let str26 = &str25.replace("QUE", "kE");
   let str27 = &str26.replace("QUI", "kI");
   let str28 = &str27.replace("Q", "k");
   let str29 = &str28.replace("R", "ɾ");
   let str30 = &str29.replace("T", "t̪");
   let str31 = &str30.replace("W", "ɰ");
   let str32 = &str31.replace("Y", "d͡ʒ");
   let str33 = &str32.replace("J", "d͡ʒ");
   let str34 = &str33.replace("F", "ɸ");
   let str35 = &str34.replace("L", "l");
   let str36 = &str35.replace("Z", "S");
   let str37 = &str36.replace("Ç", "S");
   let str38 = &str37.replace("S", "s̺");
   let str39 = &str38.replace("V", "ɰ");
   let str40 = &str39.replace("b", "β");
   let str41 = &str40.replace("cue", "kue");
   let str42 = &str41.replace("Cue", "kue");
   let str43 = &str42.replace("cui", "kui");
   let str44 = &str43.replace("Cui", "kui");
   let str45 = &str44.replace("c", "k");
   let str46 = &str45.replace("tkh", "ch");
   let str47 = &str46.replace("Tkh", "ch");
   let str48 = &str47.replace("kh", "ch");
   let str49 = &str48.replace("Kh", "ch");
   let str50 = &str49.replace("ch", "ʧ");
   let str51 = &str50.replace("d", "d");
   let str52 = &str51.replace("ng", "ŋ");
   let str53 = &str52.replace("g", "ɣ");
   let str54 = &str53.replace("n", "n̪");
   let str55 = &str54.replace("nh", "ñ");
   let str56 = &str55.replace("Nh", "ñ");
   let str57 = &str56.replace("ñ", "ɲ");
   let str58 = &str57.replace("que", "ke");
   let str59 = &str58.replace("Que", "ke");
   let str60 = &str59.replace("qui", "ki");
   let str61 = &str60.replace("Qui", "ki");
   let str62 = &str61.replace("q", "k");
   let str63 = &str62.replace("r", "ɾ");
   let str64 = &str63.replace("t", "t̪");
   let str65 = &str64.replace("y", "d͡ʒ");
   let str66 = &str65.replace("j", "d͡ʒ");
   let str67 = &str66.replace("f", "ɸ");
   let str68 = &str67.replace("z", "s");
   let str69 = &str68.replace("ç", "s");
   let str70 = &str69.replace("s", "s̺");
   let str71 = &str70.replace("v", "ɰ");
   let str72 = &str71.replace("ɡ", "ɣ");
   let str73 = &str72.replace("ã", "ɑ̃");
   let str74 = &str73.replace("õ", "ɔ̝̃");
   let str75 = &str74.replace("ũ", "ʊ̃");
   let str76 = &str75.replace("ü̃", "ɯ̃");
   let str77 = &str76.replace("a̱", "ʌ̞");
   let str78 = &str77.replace("e̱", "ɛ̝̈");
   let str79 = &str78.replace("i̱", "ɪ");
   let str80 = &str79.replace("o̱", "ɔ̝̈");
   let str81 = &str80.replace("u̱", "ʊ̱");
   let str82 = &str81.replace("ü̱", "ɯ");
   let str83 = &str82.replace("á", "a");
   let str84 = &str83.replace("é", "ɛ̝");
   let str85 = &str84.replace("í", "i");
   let str86 = &str85.replace("ó", "o");
   let str87 = &str86.replace("ú", "ʊ");
   let str88 = &str87.replace("ǘ", "ü");
   let str89 = &str88.replace("à", "a");
   let str90 = &str89.replace("è", "ɛ̝");
   let str91 = &str90.replace("ì", "i");
   let str92 = &str91.replace("ò", "o");
   let str93 = &str92.replace("ù", "ʊ");
   let str94 = &str93.replace("ǜ", "ü");
   let str95 = &str94.replace("w", "ɰ");
   let str96 = &str95.replace("d͡ʒae", "d͡ʒæː");
   let str97 = &str96.replace("a", "ɑ̈");
   let str98 = &str97.replace("e", "ɛ̝");
   let str99 = &str98.replace("o", "ɔ̝");
   let str100 = &str99.replace("u", "ʊ");
   let str101 = &str100.replace("ü", "ɯ̈");
   let str102 = &str101.replace("Ã", "ɑ̃");
   let str103 = &str102.replace("Ẽ", "ɛ̝̃");
   let str104 = &str103.replace("Ĩ", "ĩ");
   let str105 = &str104.replace("Õ", "ɔ̝̃");
   let str106 = &str105.replace("Ũ", "ʊ̃");
   let str107 = &str106.replace("Ü̃", "ɯ̃");
   let str108 = &str107.replace("A̱", "ʌ̞");
   let str109 = &str108.replace("E̱", "ɛ̝̈");
   let str110 = &str109.replace("I̱", "ɪ");
   let str111 = &str110.replace("O̱", "ɔ̝̈");
   let str112 = &str111.replace("U̱", "ʊ̱");
   let str113 = &str112.replace("Ü̱", "ɯ");
   let str114 = &str113.replace("Á", "ɑ̈");
   let str115 = &str114.replace("É", "ɛ̝");
   let str116 = &str115.replace("Í", "i");
   let str117 = &str116.replace("Ó", "ɔ̝");
   let str118 = &str117.replace("Ú", "ʊ");
   let str119 = &str118.replace("Ǘ", "Ü");
   let str120 = &str119.replace("À", "ɑ̈");
   let str121 = &str120.replace("È", "ɛ̝");
   let str122 = &str121.replace("Ì", "i");
   let str123 = &str122.replace("Ò", "ɔ̝");
   let str124 = &str123.replace("Ù", "ʊ");
   let str125 = &str124.replace("Ǜ", "Ü");
   let str126 = &str125.replace("d͡ʒAE", "d͡ʒæː");
   let str127 = &str126.replace("A", "ɑ̈");
   let str128 = &str127.replace("E", "ɛ̝");
   let str129 = &str128.replace("I", "i");
   let str130 = &str129.replace("O", "ɔ̝");
   let str131 = &str130.replace("U", "ʊ");
   let str132 = &str131.replace("Ü", "ɯ̈");
   let str133 = &str132.replace("n̪̪ɣ", "ŋ");
   let str134 = &str133.replace(". ", " ∥ ");
   let str135 = &str134.replace(".", "");
   let str136 = &str135.replace(",", " ∣");
   let str137 = &str136.replace(";", " ∥");
   let str138 = &str137.replace(":", " ∣");
   let str139 = &str138.replace("? ", " ∥ ");
   let str140 = &str139.replace("?", "");   
   let str141 = &str140.replace("¿", "");
   let str142 = &str141.replace("! ", " ∥ ");
   let str143 = &str142.replace("!", "");
   let str144 = &str143.replace("¡", "");
   let str145 = &str144.replace(" - ", " ∣ ");
   let str146 = &str145.replace(" – ", " ∣ ");
   let str147 = &str146.replace("--", " ∣ ");
   let str148 = &str147.replace("(", "∣ ");
   let result = &str148.replace(")", " ∣");
   println!("");
   println!("Eastern Tikuna (Umariaçu, BR):");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// TIKUNA: ORTHOGRAPHY

   if input1 == "--ort" && input2 == "--tca" || input1 == "--tca" && input2 == "--ort" {
// TIKUNA: BRAZIL
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("y", "j");
   let str3 = &str2.replace("Y", "J");
   let str4 = &str3.replace("ch", "tch");
   let str5 = &str4.replace("Ch", "Tch");
   let str6 = &str5.replace("CH", "TCH");
   let str7 = &str6.replace("ttch", "tch");
   let str8 = &str7.replace("Ttch", "Tch");
   let str9 = &str8.replace("TTCH", "TCH");
   let str10 = &str9.replace("ñ", "nh");
   let str11 = &str10.replace("Ñ", "NH");
   let str12 = &str11.replace("ka", "ca");
   let str13 = &str12.replace("Ka", "Ca");
   let str14 = &str13.replace("KA", "CA");
   let str15 = &str14.replace("ka̱", "ca");
   let str16 = &str15.replace("Ka̱", "Ca");
   let str17 = &str16.replace("KA̱", "CA");
   let str18 = &str17.replace("ká", "cá");
   let str19 = &str18.replace("Ká", "Cá");
   let str20 = &str19.replace("KÁ", "CÁ");
   let str21 = &str20.replace("ko", "co");
   let str22 = &str21.replace("Ko", "Co");
   let str23 = &str22.replace("KO", "CO");
   let str24 = &str23.replace("kõ", "cõ");
   let str25 = &str24.replace("Kõ", "Cõ");
   let str26 = &str25.replace("KÕ", "CÕ");
   let str27 = &str26.replace("kó", "có");
   let str28 = &str27.replace("Kó", "Có");
   let str29 = &str28.replace("KÓ", "CÓ");
   let str30 = &str29.replace("ku", "cu");
   let str31 = &str30.replace("Ku", "Cu");
   let str32 = &str31.replace("KU", "CU");
   let str33 = &str32.replace("ku̱", "cu’");
   let str34 = &str33.replace("Ku̱", "Cu’");
   let str35 = &str34.replace("KU̱", "CU’");
   let str36 = &str35.replace("kú", "cú");
   let str37 = &str36.replace("Kú", "Cú");
   let str38 = &str37.replace("KÚ", "CÚ");
   let str39 = &str38.replace("kü", "cü");
   let str40 = &str39.replace("Kü", "Cü");
   let str41 = &str40.replace("KÜ", "CÜ");
   let str42 = &str41.replace("kü’", "cü’");
   let str43 = &str42.replace("Kü’", "Cü’");
   let str44 = &str43.replace("KÜ’", "CÜ’");
   let str45 = &str44.replace("cua", "qua");
   let str46 = &str45.replace("Cua", "Qua");
   let str47 = &str46.replace("CUA", "QUA");
   let str48 = &str47.replace("cua̱", "qua’");
   let str49 = &str48.replace("Cua̱", "Qua’");
   let str50 = &str49.replace("CUA̱", "QUA’");
   let str51 = &str50.replace("kua", "qua");
   let str52 = &str51.replace("Kua", "Qua");
   let str53 = &str52.replace("KUA", "QUA");
   let str54 = &str53.replace("kua̱", "qua’");
   let str55 = &str54.replace("Kua̱", "Qua’");
   let str56 = &str55.replace("KUA̱", "QUA’");
   let str57 = &str56.replace("ki", "qui");
   let str58 = &str57.replace("Ki", "Qui");
   let str59 = &str58.replace("KI", "QUI");
   let str60 = &str59.replace("ke", "que");
   let str61 = &str60.replace("Ke", "Que");
   let str62 = &str61.replace("KE", "QUE");
   let str63 = &str62.replace("ax", "a’");
   let str64 = &str63.replace("ãx", "ã’");
   let str65 = &str64.replace("a̱x", "a’");
   let str66 = &str65.replace("ã̱x", "ã’");
   let str67 = &str66.replace("áx", "á’");
   let str68 = &str67.replace("ex", "e’");
   let str69 = &str68.replace("ẽx", "ẽ’");
   let str70 = &str69.replace("e̱x", "e’");
   let str71 = &str70.replace("ẽ̱x", "ẽ’");
   let str72 = &str71.replace("éx", "é’");
   let str73 = &str72.replace("ix", "i’");
   let str74 = &str73.replace("ĩx", "ĩ’");
   let str75 = &str74.replace("íx", "í’");
   let str76 = &str75.replace("ox", "o’");
   let str77 = &str76.replace("õx", "õ’");
   let str78 = &str77.replace("o̱x", "o’");
   let str79 = &str78.replace("õ̱x", "õ’");
   let str80 = &str79.replace("óx", "ó’");
   let str81 = &str80.replace("ux", "u’");
   let str82 = &str81.replace("ũx", "ũ’");
   let str83 = &str82.replace("u̱x", "u’");
   let str84 = &str83.replace("úx", "ú’");
   let str85 = &str84.replace("üx", "ü’");
   let str86 = &str85.replace("ü̃x", "ü̃’");
   let str87 = &str86.replace("ü̱x", "ü’");
   let str88 = &str87.replace("ü̱̃x", "ü̃’");
   let str89 = &str88.replace("ǘx", "ǘ’");
   let str90 = &str89.replace("AX", "A’");
   let str91 = &str90.replace("ÃX", "Ã’");
   let str92 = &str91.replace("A̱X", "A’");
   let str93 = &str92.replace("Ã̱X", "Ã’");
   let str94 = &str93.replace("ÁX", "Á’");
   let str95 = &str94.replace("EX", "E’");
   let str96 = &str95.replace("ẼX", "Ẽ’");
   let str97 = &str96.replace("E̱X", "E’");
   let str98 = &str97.replace("Ẽ̱X", "Ẽ’");
   let str99 = &str98.replace("ÉX", "É’");
   let str100 = &str99.replace("IX", "I’");
   let str101 = &str100.replace("ĨX", "Ĩ’");
   let str102 = &str101.replace("I̱X", "I’");
   let str103 = &str102.replace("Ĩ̱X", "Ĩ’");
   let str104 = &str103.replace("ÍX", "Í’");
   let str105 = &str104.replace("OX", "O’");
   let str106 = &str105.replace("ÕX", "Õ’");
   let str107 = &str106.replace("O̱X", "O’");
   let str108 = &str107.replace("Õ̱X", "Õ’");
   let str109 = &str108.replace("ÓX", "Ó’");
   let str110 = &str109.replace("UX", "U’");
   let str111 = &str110.replace("ŨX", "Ũ’");
   let str112 = &str111.replace("U̱X", "U’");
   let str113 = &str112.replace("Ũ̱X", "Ũ’");
   let str114 = &str113.replace("ÚX", "Ú’");
   let str115 = &str114.replace("ÜX", "Ü’");
   let str116 = &str115.replace("Ü̃X", "Ü̃’");
   let str117 = &str116.replace("Ü̱X", "Ü’");
   let str118 = &str117.replace("Ü̱̃X", "Ü̃’");
   let str119 = &str118.replace("ǗX", "Ǘ’");
   let str120 = &str119.replace("Ax", "A’");
   let str121 = &str120.replace("Ãx", "Ã’");
   let str122 = &str121.replace("A̱x", "A’");
   let str123 = &str122.replace("Ã̱x", "Ã’");
   let str124 = &str123.replace("Áx", "Á’");
   let str125 = &str124.replace("Ex", "E’");
   let str126 = &str125.replace("Ẽx", "Ẽ’");
   let str127 = &str126.replace("E̱x", "E’");
   let str128 = &str127.replace("Ẽ̱x", "Ẽ’");
   let str129 = &str128.replace("Éx", "É’");
   let str130 = &str129.replace("Ix", "I’");
   let str131 = &str130.replace("Ĩx", "Ĩ’");
   let str132 = &str131.replace("Íx", "Í’");
   let str133 = &str132.replace("Ox", "O’");
   let str134 = &str133.replace("Õx", "Õ’");
   let str135 = &str134.replace("O̱x", "O’");
   let str136 = &str135.replace("Õ̱x", "Õ’");
   let str137 = &str136.replace("Óx", "Ó’");
   let str138 = &str137.replace("Ux", "U’");
   let str139 = &str138.replace("Ũx", "Ũ’");
   let str140 = &str139.replace("U̱x", "U’");
   let str141 = &str140.replace("Ũ̱x", "Ũ’");
   let str142 = &str141.replace("Úx", "Ú’");
   let str143 = &str142.replace("Üx", "Ü’");
   let str144 = &str143.replace("Ü̃x", "Ü̃’");
   let str145 = &str144.replace("Ü̱x", "Ü’");
   let str146 = &str145.replace("Ü̱̃x", "Ü̃’");
   let result = &str146.replace("Ǘx", "Ǘ’");
   println!("");
   println!("Brazil:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
// TIKUNA: COLOMBIA
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("j", "y");
   let str3 = &str2.replace("J", "Y");
   let str4 = &str3.replace("tch", "ch");
   let str5 = &str4.replace("Tch", "Ch");
   let str6 = &str5.replace("TCH", "CH");
   let str7 = &str6.replace("nh", "ñ");
   let str8 = &str7.replace("Nh", "Ñ");
   let str9 = &str8.replace("NH", "Ñ");
   let str10 = &str9.replace("c", "k");
   let str11 = &str10.replace("C", "K");
   let str12 = &str11.replace("kh", "ch");
   let str13 = &str12.replace("Kh", "Ch");
   let str14 = &str13.replace("KH", "CH");
   let str15 = &str14.replace("qui", "ki");
   let str16 = &str15.replace("Qui", "Ki");
   let str17 = &str16.replace("QUI", "KI");
   let str18 = &str17.replace("que", "ke");
   let str19 = &str18.replace("Que", "Ke");
   let str20 = &str19.replace("QUE", "KE");
   let str21 = &str20.replace("q", "k");
   let str22 = &str21.replace("Q", "K");
   let str23 = &str22.replace("x", "");
   let str24 = &str23.replace("X", "");
   let str25 = &str24.replace("'", "");
   let result = &str25.replace("’", "");
   println!("");
   println!("Colombia:");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
// TIKUNA: ILV
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("j", "y");
   let str3 = &str2.replace("J", "Y");
   let str4 = &str3.replace("tch", "ch");
   let str5 = &str4.replace("Tch", "Ch");
   let str6 = &str5.replace("TCH", "CH");
   let str7 = &str6.replace("nh", "ñ");
   let str8 = &str7.replace("Nh", "Ñ");
   let str9 = &str8.replace("NH", "Ñ");
   let str10 = &str9.replace("q", "c");
   let str11 = &str10.replace("Q", "C");
   let str12 = &str11.replace("à", "a");
   let str13 = &str12.replace("ò", "o");
   let str14 = &str13.replace("è", "e");
   let str15 = &str14.replace("ì", "i");
   let str16 = &str15.replace("ù", "u");
   let str17 = &str16.replace("ǜ", "ü");
   let str18 = &str17.replace("À", "A");
   let str19 = &str18.replace("Ò", "O");
   let str20 = &str19.replace("È", "E");
   let str21 = &str20.replace("Ì", "I");
   let str22 = &str21.replace("Ù", "U");
   let str23 = &str22.replace("Ǜ", "Ü");
   let str24 = &str23.replace("ki", "qui");
   let str25 = &str24.replace("Ki", "Qui");
   let str26 = &str25.replace("KI", "QUI");
   let str27 = &str26.replace("ke", "que");
   let str28 = &str27.replace("Ke", "Que");
   let str29 = &str28.replace("KE", "QUE");
   let str30 = &str29.replace("kí", "quí");
   let str31 = &str30.replace("Kí", "Quí");
   let str32 = &str31.replace("KÍ", "QUÍ");
   let str33 = &str32.replace("ké", "qué");
   let str34 = &str33.replace("Ké", "Qué");
   let str35 = &str34.replace("KÉ", "QUÉ");
   let str36 = &str35.replace("k", "c");
   let str37 = &str36.replace("K", "C");
   let str38 = &str37.replace("a'", "ax");
   let str39 = &str38.replace("ã'", "ãx");
   let str40 = &str39.replace("a̱'", "a̱x");
   let str41 = &str40.replace("ã̱'", "ã̱x");
   let str42 = &str41.replace("á'", "áx");
   let str43 = &str42.replace("e'", "ex");
   let str44 = &str43.replace("ẽ'", "ẽx");
   let str45 = &str44.replace("e̱'", "e̱x");
   let str46 = &str45.replace("ẽ̱'", "ẽ̱x");
   let str47 = &str46.replace("é'", "éx");
   let str48 = &str47.replace("i'", "ix");
   let str49 = &str48.replace("ĩ'", "ĩx");
   let str50 = &str49.replace("i̱'", "i̱x");
   let str51 = &str50.replace("ĩ̱'", "ĩ̱x");
   let str52 = &str51.replace("í'", "íx");
   let str53 = &str52.replace("o'", "ox");
   let str54 = &str53.replace("õ'", "õx");
   let str55 = &str54.replace("o̱'", "o̱x");
   let str56 = &str55.replace("õ̱'", "õ̱x");
   let str57 = &str56.replace("ó'", "óx");
   let str58 = &str57.replace("u'", "ux");
   let str59 = &str58.replace("ũ'", "ũx");
   let str60 = &str59.replace("u̱'", "u̱x");
   let str61 = &str60.replace("ũ̱'", "ũ̱x");
   let str62 = &str61.replace("ú'", "úx");
   let str63 = &str62.replace("ü'", "üx");
   let str64 = &str63.replace("ü̃'", "ü̃x");
   let str65 = &str64.replace("ü̱'", "ü̱x");
   let str66 = &str65.replace("ü̱̃'", "ü̱̃x");
   let str67 = &str66.replace("ǘ'", "ǘx");
   let str68 = &str67.replace("'", "x");
   let str69 = &str68.replace("a’", "ax");
   let str70 = &str69.replace("ã’", "ãx");
   let str71 = &str70.replace("a̱’", "a̱x");
   let str72 = &str71.replace("ã̱’", "ã̱x");
   let str73 = &str72.replace("á’", "áx");
   let str74 = &str73.replace("e’", "ex");
   let str75 = &str74.replace("ẽ’", "ẽx");
   let str76 = &str75.replace("e̱’", "e̱x");
   let str77 = &str76.replace("ẽ̱’", "ẽ̱x");
   let str78 = &str77.replace("é’", "éx");
   let str79 = &str78.replace("i’", "ix");
   let str80 = &str79.replace("ĩ’", "ĩx");
   let str81 = &str80.replace("i̱’", "i̱x");
   let str82 = &str81.replace("ĩ̱’", "ĩ̱x");
   let str83 = &str82.replace("í’", "íx");
   let str84 = &str83.replace("o’", "ox");
   let str85 = &str84.replace("õ’", "õx");
   let str86 = &str85.replace("o̱’", "o̱x");
   let str87 = &str86.replace("õ̱’", "õ̱x");
   let str88 = &str87.replace("ó’", "óx");
   let str89 = &str88.replace("u’", "ux");
   let str90 = &str89.replace("ũ’", "ũx");
   let str91 = &str90.replace("u̱’", "u̱x");
   let str92 = &str91.replace("ũ̱’", "ũ̱x");
   let str93 = &str92.replace("ú’", "úx");
   let str94 = &str93.replace("ü’", "üx");
   let str95 = &str94.replace("ü̃’", "ü̃x");
   let str96 = &str95.replace("ü̱’", "ü̱x");
   let str97 = &str96.replace("ü̱̃’", "ü̱̃x");
   let str98 = &str97.replace("ǘ’", "ǘx");
   let result = &str98.replace("’", "x");
   println!("");
   println!("Peru (ILV):");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
// TIKUNA: FORMABIAP
   let str1 = args.get(3).expect("No string inserted! See: --help");
   let str2 = &str1.replace("j", "y");
   let str3 = &str2.replace("J", "Y");
   let str4 = &str3.replace("tch", "ch");
   let str5 = &str4.replace("Tch", "Ch");
   let str6 = &str5.replace("TCH", "CH");
   let str7 = &str6.replace("nh", "ñ");
   let str8 = &str7.replace("Nh", "Ñ");
   let str9 = &str8.replace("NH", "Ñ");
   let str10 = &str9.replace("à", "a");
   let str11 = &str10.replace("ò", "o");
   let str12 = &str11.replace("è", "e");
   let str13 = &str12.replace("ì", "i");
   let str14 = &str13.replace("ù", "u");
   let str15 = &str14.replace("ǜ", "ü");
   let str16 = &str15.replace("À", "A");
   let str17 = &str16.replace("Ò", "O");
   let str18 = &str17.replace("È", "E");
   let str19 = &str18.replace("Ì", "I");
   let str20 = &str19.replace("Ù", "U");
   let str21 = &str20.replace("Ǜ", "Ü");
   let str22 = &str21.replace("á", "a");
   let str23 = &str22.replace("ó", "o");
   let str24 = &str23.replace("é", "e");
   let str25 = &str24.replace("í", "i");
   let str26 = &str25.replace("ú", "u");
   let str27 = &str26.replace("ǘ", "ü");
   let str28 = &str27.replace("Á", "A");
   let str29 = &str28.replace("É", "E");
   let str30 = &str29.replace("Í", "I");
   let str31 = &str30.replace("Ó", "O");
   let str32 = &str31.replace("Ú", "U");
   let str33 = &str32.replace("Ǘ", "Ü");
   let str34 = &str33.replace("c", "k");
   let str35 = &str34.replace("C", "K");
   let str36 = &str35.replace("kh", "ch");
   let str37 = &str36.replace("Kh", "Ch");
   let str38 = &str37.replace("KH", "CH");
   let str39 = &str38.replace("qui", "ki");
   let str40 = &str39.replace("Qui", "Ki");
   let str41 = &str40.replace("QUI", "KI");
   let str42 = &str41.replace("que", "ke");
   let str43 = &str42.replace("Que", "Ke");
   let str44 = &str43.replace("QUE", "KE");
   let str45 = &str44.replace("q", "k");
   let str46 = &str45.replace("Q", "K");
   let str47 = &str46.replace("a'", "ax");
   let str48 = &str47.replace("ã'", "ãx");
   let str49 = &str48.replace("a̱'", "ax");
   let str50 = &str49.replace("ã̱'", "ãx");
   let str51 = &str50.replace("e'", "ex");
   let str52 = &str51.replace("ẽ'", "ẽx");
   let str53 = &str52.replace("e̱'", "ex");
   let str54 = &str53.replace("ẽ̱'", "ẽx");
   let str55 = &str54.replace("i'", "ix");
   let str56 = &str55.replace("ĩ'", "ĩx");
   let str57 = &str56.replace("i̱'", "ix");
   let str58 = &str57.replace("ĩ̱'", "ĩx");
   let str59 = &str58.replace("o'", "ox");
   let str60 = &str59.replace("õ'", "õx");
   let str61 = &str60.replace("o̱'", "ox");
   let str62 = &str61.replace("õ̱'", "õx");
   let str63 = &str62.replace("u'", "ux");
   let str64 = &str63.replace("ũ'", "ũx");
   let str65 = &str64.replace("u̱'", "ux");
   let str66 = &str65.replace("ũ̱'", "ũx");
   let str67 = &str66.replace("ü'", "üx");
   let str68 = &str67.replace("ü̃'", "ü̃x");
   let str69 = &str68.replace("ü̱'", "üx");
   let str70 = &str69.replace("ü̱̃'", "ü̃x");
   let str71 = &str70.replace("A̱", "AX");
   let str72 = &str71.replace("Ã̱", "ÃX");
   let str73 = &str72.replace("E̱", "EX");
   let str74 = &str73.replace("Ẽ̱", "ẼX");
   let str75 = &str74.replace("I̱", "IX");
   let str76 = &str75.replace("Ĩ̱", "ĨX");
   let str77 = &str76.replace("O̱", "OX");
   let str78 = &str77.replace("Õ̱", "ÕX");
   let str79 = &str78.replace("U̱", "UX");
   let str80 = &str79.replace("Ũ̱", "ŨX");
   let str81 = &str80.replace("Ü̱", "ÜX");
   let str82 = &str81.replace("Ü̱̃", "Ü̃X");
   let str83 = &str82.replace("'", "x");
   let str84 = &str83.replace("a’", "ax");
   let str85 = &str84.replace("ã’", "ãx");
   let str86 = &str85.replace("a̱’", "ax");
   let str87 = &str86.replace("ã̱’", "ãx");
   let str88 = &str87.replace("e’", "ex");
   let str89 = &str88.replace("ẽ’", "ẽx");
   let str90 = &str89.replace("e̱’", "ex");
   let str91 = &str90.replace("ẽ̱’", "ẽx");
   let str92 = &str91.replace("i’", "ix");
   let str93 = &str92.replace("ĩ’", "ĩx");
   let str94 = &str93.replace("i̱’", "ix");
   let str95 = &str94.replace("ĩ̱’", "ĩx");
   let str96 = &str95.replace("o’", "ox");
   let str97 = &str96.replace("õ’", "õx");
   let str98 = &str97.replace("o̱’", "ox");
   let str99 = &str98.replace("õ̱’", "õx");
   let str100 = &str99.replace("u’", "ux");
   let str101 = &str100.replace("ũ’", "ũx");
   let str102 = &str101.replace("u̱’", "ux");
   let str103 = &str102.replace("ũ̱’", "ũx");
   let str104 = &str103.replace("ü’", "üx");
   let str105 = &str104.replace("ü̃’", "ü̃x");
   let str106 = &str105.replace("ü̱’", "üx");
   let str107 = &str106.replace("ü̱̃’", "ü̃x");
   let result = &str107.replace("’", "x");
   println!("");
   println!("Peru (FORMABIAP):");
   println!("");
   print!("{}", bright_yellow);
   println!("{}", result);
   print!("{}", clear);
   println!("");
   let exit_code = fake_main();
   exit(exit_code);
   }

// INVALID &ARGS[1] AND/OR &ARGS[2]

   println!("Error: Invalid arguments provided! See: --help");

}
